apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-w5vq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-w5vq
    app.kubernetes.io/part-of: load-app-4443a3b0-679e-4960-9f1a-9c91e48b2a6a
  name: devfile-sample-go-basic-w5vq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-w5vq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-w5vq
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-79-tenant/load-app-4443a3b0-679e-4960-9f1a-9c91e48b2a6a/devfile-sample-go-basic-w5vq@sha256:3afc04832bc3c4e9b21529652c16bca57c7baa8de6aaaf616ed3e5043748b31c
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
